from __future__ import annotations
from typing import Optional, Protocol
from apps.file_upload.domain.models.dto import UploadCtx, UploadPlan


class SessionRepository(Protocol):
    def create_session(self, ctx: UploadCtx, plan: UploadPlan) -> None: ...
    def set_status(self, session_id: str, status: str) -> None: ...
    def mark_available(self, session_id: str, bucket: str, key: str) -> None: ...
    def mark_error(self, session_id: str, code: str, message: str) -> None: ...
    def save_multipart_id(self, session_id: str, mpu_upload_id: str) -> None: ...
    def get_ctx(self, session_id: str):
        """Return UploadCtx for session_id."""
        ...

    def get_plan(self, session_id: str) -> UploadPlan: ...
    def get_multipart_id(self, session_id: str) -> Optional[str]: ...
    def abort_multipart(self, session_id: str) -> Optional[dict]: ...
