# Generated by Django 5.2.8 on 2025-11-23 21:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_batch',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('bucket', models.CharField(max_length=128)),
                ('key', models.CharField(db_index=True, max_length=1024)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('storage_class', models.CharField(blank=True, max_length=32)),
                ('etag', models.CharField(blank=True, max_length=128)),
                ('checksum_sha256', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('available', 'Available'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], db_index=True, default='available', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='file_upload.uploadbatch')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['user', 'created_at'], name='upload_batc_user_id_d8d450_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user', 'created_at'], name='file_user_id_1d2926_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['status', 'created_at'], name='file_status_e588ae_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['bucket', 'key'], name='file_bucket_cf5104_idx'),
        ),
    ]
